# Generated by Django 4.2.9 on 2024-01-29 17:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='package',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256)),
                ('price', models.FloatField(max_length=256)),
                ('description', models.TextField()),
                ('dest_from', models.CharField(max_length=256)),
                ('dest_to', models.CharField(max_length=256)),
                ('img', models.ImageField(upload_to='media')),
            ],
        ),
    ]
