# Generated by Django 5.0.6 on 2024-06-05 12:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_day_activity'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='day',
            name='package',
        ),
        migrations.DeleteModel(
            name='Activity',
        ),
        migrations.DeleteModel(
            name='Day',
        ),
    ]
