# Generated by Django 5.0.6 on 2024-06-06 11:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_day'),
    ]

    operations = [
        migrations.AddField(
            model_name='package',
            name='Excluded',
            field=models.TextField(default='NO conditions'),
        ),
        migrations.AddField(
            model_name='package',
            name='Included',
            field=models.TextField(default='NO conditions'),
        ),
        migrations.CreateModel(
            name='Hotel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('city', models.CharField(max_length=50)),
                ('star_rating', models.IntegerField()),
                ('website', models.URLField()),
                ('package', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hotel', to='core.package')),
            ],
        ),
    ]
