# Generated by Django 5.0.6 on 2024-07-01 02:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_hotel_img'),
    ]

    operations = [
        migrations.CreateModel(
            name='gallery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='')),
                ('package', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gallery', to='core.package')),
            ],
        ),
    ]
